version: '3'  # version of compose format 

services:
  website:
    image: php:apache 
    container_name: 'brevet_website'
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5000:80  # host:container
    depends_on:
      - api  # website is not going to work unless api is running

  api:
    build: ./brevet_api
    container_name: 'brevet_api'
    volumes:
      - ./brevet_api:/usr/src/app 
    ports:
      - 5001:80  # host:container
    depends_on:
      - mongo

  brevet:
    build: ./brevet 
    container_name: 'brevet_server'
    volumes:
      - ./brevet:/app
    ports:
      - 5002:5000  # host:container
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: 'brevet_db'
    volumes: 
      - 'mongo:/data/db'
    ports: 
      - 27017:27017

volumes:
  mongo: